
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true 
  
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    username: test
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  
  sql:
    init:
      mode: always

app:
  jwt:
    secret: letitgobaby

# logging:
#   level:
#     org:
#       springframework:
#         security:
#           web:
#             FilterChainProxy: DEBUG

